services:
  detectron2:
    build: .
    container_name: detectron2_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - JUPYTER_TOKEN=detectron2
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    ports:
      - "8888:8888"  # for Jupyter
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='detectron2'
